modLoader="javafml"
loaderVersion="[26,)"
issueTrackerURL="http://my.issue.tracker/"
displayURL="http://example.com/"
logoFile="supertools_logo.png"

[[mods]]
modId="supertools"
version="${file.jarVersion}"
displayName="Super Tools"
updateJSONURL="http://myurl.me/"


credits="Textures by: TheLuigiplayer, Code by: KiritoGames20"
authors="KiritoGames20 & TheLuigiplayer"
description='''
The SuperTools Mod.It adds Lapis-,Redstone-,Quartz- & Emerald Tools. Made by TheLuigiplayer & KiritoGames20

'''


[[dependencies.supertools]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[26,)" #mandatory
    ordering="NONE"
    side="BOTH"


[[dependencies.supertools]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.2]"
    ordering="NONE"
    side="BOTH"